const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const distRoot = path.resolve(root, 'dist');
const webDir = path.resolve(distRoot, 'web');
const lockPath = path.resolve(distRoot, '.stage-web.lock');

if (!webDir.startsWith(distRoot + path.sep)) {
  throw new Error(`Refusing to stage outside dist: ${webDir}`);
}

const include = [
  /^nba2k26-build-tracker\.html$/,
  /^nba2k26-.*\.(?:css|js|svg)$/,
  /^(?:icon\.svg|manifest\.json|og-image\.png|sw\.js)$/,
];

function sleep(ms) {
  Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, ms);
}

function acquireLock() {
  fs.mkdirSync(distRoot, { recursive: true });
  for (let attempt = 0; attempt < 100; attempt++) {
    try {
      return fs.openSync(lockPath, 'wx');
    } catch (error) {
      if (error.code !== 'EEXIST') throw error;
      const ageMs = Date.now() - fs.statSync(lockPath).mtimeMs;
      if (ageMs > 5 * 60 * 1000) {
        fs.rmSync(lockPath, { force: true });
        continue;
      }
      sleep(100);
    }
  }
  throw new Error(`Timed out waiting for staging lock: ${lockPath}`);
}

const lock = acquireLock();

try {
  fs.rmSync(webDir, { recursive: true, force: true });
  fs.mkdirSync(webDir, { recursive: true });

  const sourceFiles = fs.readdirSync(root)
    .filter(file => include.some(pattern => pattern.test(file)))
    .sort();

  for (const file of sourceFiles) {
    fs.copyFileSync(path.join(root, file), path.join(webDir, file));
  }

  fs.copyFileSync(
    path.join(root, 'nba2k26-build-tracker.html'),
    path.join(webDir, 'index.html'),
  );

  const manifestPath = path.join(webDir, 'manifest.json');
  const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
  manifest.start_url = './index.html';
  fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + '\n');

  const runtimeConfig = [
    '// Generated by scripts/stage-web.cjs. Public anon keys are safe to bundle.',
    '(function(window) {',
    "  'use strict';",
    '',
    '  window.NBA2K26_RUNTIME_CONFIG = Object.freeze({',
    `    supabaseUrl: ${JSON.stringify(process.env.NBA2K26_SUPABASE_URL || '')},`,
    `    supabaseAnonKey: ${JSON.stringify(process.env.NBA2K26_SUPABASE_ANON_KEY || '')},`,
    '  });',
    '})(window);',
    '',
  ].join('\n');

  fs.writeFileSync(path.join(webDir, 'nba2k26-runtime-config.js'), runtimeConfig);

  const hasCloudDefaults = !!(
    process.env.NBA2K26_SUPABASE_URL &&
    process.env.NBA2K26_SUPABASE_ANON_KEY
  );

  console.log(`staged ${sourceFiles.length} source assets plus index.html to ${webDir}`);
  console.log(`cloud defaults: ${hasCloudDefaults ? 'embedded public config' : 'manual setup remains available'}`);
} finally {
  fs.closeSync(lock);
  fs.rmSync(lockPath, { force: true });
}
